### PR TITLE
Publishing strategy

### PR DESCRIPTION
**Pull request by kand**
Added release script to use to release bulbs-cms-2 for usage on other projects.

### CODE REVIEW

**Comment by kand** [comment]
@mparent61 @spra85 @collin this will be the new way to create releases for ```bulbs-cms```.

**Comment by mparent61** [comment]
This is looking good. 
Couple thoughts:
1) Is 'clean' automatically triggered as part of the release process? This should be required to avoid orphaned static files
2) Any thought on how this release process would be replicated to other NPM projects? Would be ideal to avoid copying all of these scripts into every project.

**Comment by kand** [comment]
1. A bit indirect, but the release script calls ```grunt build``` which calls a grunt clean task before build.
2. We could probably put this into another project and require it as an npm dependency. We don't have too many other serious npm projects that need to be packaged up before use at the moment though, so I think this is a good start.

**Comment by collin** [comment]
We could re-use the script utilities that have been installed into our sites.

@kand right now the shared site scripts are split across `site-scripts` and `onion-sub` repositories. Installation of these projects into the sites is handled through git subtrees. We could have a similar set-up for packages with a `package-scripts` repo (`onion-sub` can be re-used, as it deals in script running and maintenance tasks.)

When you get a moment I can talk you through the current state of affairs in those repos.

**Pull request merged**
